# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_pages = QtWidgets.QFrame(self.content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_bar = QtWidgets.QFrame(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_bar.sizePolicy().hasHeightForWidth())
        self.top_bar.setSizePolicy(sizePolicy)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 70))
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 70))
        self.top_bar.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setLineWidth(1)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_4.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Btn_logo = QtWidgets.QPushButton(self.frame_2)
        self.Btn_logo.setMinimumSize(QtCore.QSize(144, 60))
        self.Btn_logo.setStyleSheet("QPushButton{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/logo/logo/simplot++_logo.svg);\n"
"\n"
"}")
        self.Btn_logo.setText("")
        self.Btn_logo.setObjectName("Btn_logo")
        self.horizontalLayout_5.addWidget(self.Btn_logo)
        self.Btn_group_page = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_group_page.sizePolicy().hasHeightForWidth())
        self.Btn_group_page.setSizePolicy(sizePolicy)
        self.Btn_group_page.setMinimumSize(QtCore.QSize(125, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_group_page.setFont(font)
        self.Btn_group_page.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/group_page_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/group_page_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    image: url(:/new/disabled/disabled/group_page_grey.svg)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/group_page_pressed.svg);\n"
"}\n"
"QPushButton:checked{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/group_page_hover.svg);\n"
"}")
        self.Btn_group_page.setText("")
        self.Btn_group_page.setCheckable(True)
        self.Btn_group_page.setChecked(True)
        self.Btn_group_page.setAutoDefault(False)
        self.Btn_group_page.setDefault(False)
        self.Btn_group_page.setFlat(False)
        self.Btn_group_page.setObjectName("Btn_group_page")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.Btn_group_page)
        self.horizontalLayout_5.addWidget(self.Btn_group_page)
        self.Btn_simplot_page = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_simplot_page.sizePolicy().hasHeightForWidth())
        self.Btn_simplot_page.setSizePolicy(sizePolicy)
        self.Btn_simplot_page.setMinimumSize(QtCore.QSize(125, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_simplot_page.setFont(font)
        self.Btn_simplot_page.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    image: url(:/new/active/active/simplot_page_active.svg)\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    image: url(:/new/hover/hover/simplot_page_hover.svg)\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    image: url(:/new/disabled/disabled/simplot_page_grey.svg)\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/simplot_page_pressed.svg);\n"
"}\n"
"QPushButton:checked{\n"
"    border: 0px;\n"
"    image: url(:/new/hover/hover/simplot_page_hover.svg)\n"
"}")
        self.Btn_simplot_page.setText("")
        self.Btn_simplot_page.setCheckable(True)
        self.Btn_simplot_page.setObjectName("Btn_simplot_page")
        self.buttonGroup_4.addButton(self.Btn_simplot_page)
        self.horizontalLayout_5.addWidget(self.Btn_simplot_page)
        self.Btn_bootstrap_page = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_bootstrap_page.sizePolicy().hasHeightForWidth())
        self.Btn_bootstrap_page.setSizePolicy(sizePolicy)
        self.Btn_bootstrap_page.setMinimumSize(QtCore.QSize(125, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_bootstrap_page.setFont(font)
        self.Btn_bootstrap_page.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    image: url(:/new/active/active/Bootscan_page_active.svg)\n"
" }\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    image: url(:/new/hover/hover/Bootscan_page_hover.svg)\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    image: url(:/new/disabled/disabled/Bootscan_page_grey.svg)\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/Bootscan_page_pressed.svg);\n"
"}\n"
"QPushButton:checked{\n"
"    border: 0px;\n"
"    image: url(:/new/hover/hover/Bootscan_page_hover.svg)\n"
"}")
        self.Btn_bootstrap_page.setText("")
        self.Btn_bootstrap_page.setCheckable(True)
        self.Btn_bootstrap_page.setChecked(False)
        self.Btn_bootstrap_page.setObjectName("Btn_bootstrap_page")
        self.buttonGroup_4.addButton(self.Btn_bootstrap_page)
        self.horizontalLayout_5.addWidget(self.Btn_bootstrap_page)
        self.Btn_findSites = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_findSites.sizePolicy().hasHeightForWidth())
        self.Btn_findSites.setSizePolicy(sizePolicy)
        self.Btn_findSites.setMinimumSize(QtCore.QSize(125, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_findSites.setFont(font)
        self.Btn_findSites.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    image: url(:/new/active/active/findsite_page_active.svg)\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    image: url(:/new/hover/hover/findsite_page_hover.svg)\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/findsite_page_grey.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/findsite_page_pressed.svg);\n"
"}\n"
"QPushButton:checked{\n"
"    border: 0px;\n"
"    image: url(:/new/hover/hover/findsite_page_hover.svg)\n"
"}")
        self.Btn_findSites.setText("")
        self.Btn_findSites.setCheckable(True)
        self.Btn_findSites.setObjectName("Btn_findSites")
        self.buttonGroup_4.addButton(self.Btn_findSites)
        self.horizontalLayout_5.addWidget(self.Btn_findSites)
        self.Btn_simplot_network = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_simplot_network.sizePolicy().hasHeightForWidth())
        self.Btn_simplot_network.setSizePolicy(sizePolicy)
        self.Btn_simplot_network.setMinimumSize(QtCore.QSize(125, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_simplot_network.setFont(font)
        self.Btn_simplot_network.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    image: url(:/new/active/active/network_page_active.svg)\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    image: url(:/new/hover/hover/network_page_hover.svg)\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    image: url(:/new/disabled/disabled/network_page_grey.svg)\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/network_page_pressed.svg);\n"
"}\n"
"QPushButton:checked{\n"
"    border: 0px;\n"
"    image: url(:/new/hover/hover/network_page_hover.svg)\n"
"}")
        self.Btn_simplot_network.setText("")
        self.Btn_simplot_network.setCheckable(True)
        self.Btn_simplot_network.setObjectName("Btn_simplot_network")
        self.buttonGroup_4.addButton(self.Btn_simplot_network)
        self.horizontalLayout_5.addWidget(self.Btn_simplot_network)
        self.Btn_recombination_test = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_recombination_test.sizePolicy().hasHeightForWidth())
        self.Btn_recombination_test.setSizePolicy(sizePolicy)
        self.Btn_recombination_test.setMinimumSize(QtCore.QSize(125, 60))
        self.Btn_recombination_test.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/recombination_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/recombination_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/recombination_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/recombination_pressed.svg);\n"
"}\n"
"QPushButton:checked{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/recombination_hover.svg);\n"
"}")
        self.Btn_recombination_test.setText("")
        self.Btn_recombination_test.setCheckable(True)
        self.Btn_recombination_test.setObjectName("Btn_recombination_test")
        self.buttonGroup_4.addButton(self.Btn_recombination_test)
        self.horizontalLayout_5.addWidget(self.Btn_recombination_test)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(125, 60))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/question_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/question_hover.svg);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/question_pressed.svg);\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.horizontalLayout_4.addWidget(self.frame_2, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.top_bar)
        self.progressBar_global = QtWidgets.QProgressBar(self.frame_pages)
        self.progressBar_global.setMinimumSize(QtCore.QSize(0, 9))
        self.progressBar_global.setMaximumSize(QtCore.QSize(16777215, 9))
        self.progressBar_global.setAutoFillBackground(False)
        self.progressBar_global.setStyleSheet("QProgressBar {\n"
"     border: 3px;\n"
"     border-radius: 1px;\n"
"    background-color: rgb(239, 239, 239);\n"
" }\n"
" QProgressBar::chunk {\n"
"    \n"
"    background-color: rgb(143, 17, 20);\n"
" }")
        self.progressBar_global.setProperty("value", 0)
        self.progressBar_global.setTextVisible(False)
        self.progressBar_global.setInvertedAppearance(False)
        self.progressBar_global.setObjectName("progressBar_global")
        self.verticalLayout_2.addWidget(self.progressBar_global)
        self.Pages_Widget = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.group_page = QtWidgets.QWidget()
        self.group_page.setObjectName("group_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.group_page)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.page_1_option_bar = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_1_option_bar.sizePolicy().hasHeightForWidth())
        self.page_1_option_bar.setSizePolicy(sizePolicy)
        self.page_1_option_bar.setMinimumSize(QtCore.QSize(145, 0))
        self.page_1_option_bar.setMaximumSize(QtCore.QSize(81, 16777215))
        self.page_1_option_bar.setStyleSheet("")
        self.page_1_option_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_1_option_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page_1_option_bar.setObjectName("page_1_option_bar")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_1_option_bar)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Btn_File_Browser = QtWidgets.QPushButton(self.page_1_option_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_File_Browser.sizePolicy().hasHeightForWidth())
        self.Btn_File_Browser.setSizePolicy(sizePolicy)
        self.Btn_File_Browser.setMinimumSize(QtCore.QSize(142, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_File_Browser.setFont(font)
        self.Btn_File_Browser.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/browse_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/browse_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/browse_grey.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/browse_pressed.svg);\n"
"}")
        self.Btn_File_Browser.setText("")
        self.Btn_File_Browser.setObjectName("Btn_File_Browser")
        self.verticalLayout_6.addWidget(self.Btn_File_Browser)
        self.Btn_reopen = QtWidgets.QPushButton(self.page_1_option_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_reopen.sizePolicy().hasHeightForWidth())
        self.Btn_reopen.setSizePolicy(sizePolicy)
        self.Btn_reopen.setMinimumSize(QtCore.QSize(142, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_reopen.setFont(font)
        self.Btn_reopen.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Btn_reopen.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/reopen_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/reopen_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/reopen_grey.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/reopen_pressed.svg);\n"
"}")
        self.Btn_reopen.setText("")
        self.Btn_reopen.setObjectName("Btn_reopen")
        self.verticalLayout_6.addWidget(self.Btn_reopen)
        self.Btn_save_nexus = QtWidgets.QPushButton(self.page_1_option_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_save_nexus.sizePolicy().hasHeightForWidth())
        self.Btn_save_nexus.setSizePolicy(sizePolicy)
        self.Btn_save_nexus.setMinimumSize(QtCore.QSize(142, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_save_nexus.setFont(font)
        self.Btn_save_nexus.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/save_groups_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/save_groups_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/save_groups_grey.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/save_groups_pressed.svg);\n"
"}")
        self.Btn_save_nexus.setText("")
        self.Btn_save_nexus.setObjectName("Btn_save_nexus")
        self.verticalLayout_6.addWidget(self.Btn_save_nexus)
        self.Btn_user_pref = QtWidgets.QPushButton(self.page_1_option_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_user_pref.sizePolicy().hasHeightForWidth())
        self.Btn_user_pref.setSizePolicy(sizePolicy)
        self.Btn_user_pref.setMinimumSize(QtCore.QSize(140, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_user_pref.setFont(font)
        self.Btn_user_pref.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/user_pref_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/user_pref_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/user_pref_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/user_pref_pressed.svg);\n"
"}")
        self.Btn_user_pref.setText("")
        self.Btn_user_pref.setObjectName("Btn_user_pref")
        self.verticalLayout_6.addWidget(self.Btn_user_pref)
        self.horizontalLayout_2.addWidget(self.page_1_option_bar, 0, QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(275, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(10, 0, 10, 20)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.listWidget_groups = QtWidgets.QListWidget(self.frame_4)
        self.listWidget_groups.setMinimumSize(QtCore.QSize(325, 0))
        self.listWidget_groups.setMaximumSize(QtCore.QSize(325, 16777215))
        self.listWidget_groups.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget_groups.setStyleSheet("QListWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListWidget QScrollbar{\n"
"background: rgb(207, 207, 207);\n"
"}\n"
"\n"
"QListView::item:selected{\n"
"border: 1px solid black;\n"
"background: grey;\n"
"}")
        self.listWidget_groups.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget_groups.setObjectName("listWidget_groups")
        self.verticalLayout_4.addWidget(self.listWidget_groups)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(84, 250))
        self.frame_5.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 15, 6, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Btn_add = QtWidgets.QPushButton(self.frame_5)
        self.Btn_add.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_add.setFont(font)
        self.Btn_add.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(0, 52, 76);\n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(207, 207, 207);\n"
"    border: 2px solid rgb(0, 52, 76);\n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(160, 160, 160);\n"
"    border: 2px solid rgb(0, 52, 76);\n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 2px solid rgb(160, 160, 160);\n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"    color: rgb(160, 160, 160);\n"
"}\n"
"")
        self.Btn_add.setObjectName("Btn_add")
        self.verticalLayout_5.addWidget(self.Btn_add)
        self.Btn_del = QtWidgets.QPushButton(self.frame_5)
        self.Btn_del.setMinimumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_del.setFont(font)
        self.Btn_del.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(0, 52, 76);\n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(207, 207, 207);\n"
"    border: 2px solid rgb(0, 52, 76);\n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(160, 160, 160);\n"
"    border: 2px solid rgb(0, 52, 76);\n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 2px solid rgb(160, 160, 160);\n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"    color: rgb(160, 160, 160);\n"
"}\n"
"")
        self.Btn_del.setObjectName("Btn_del")
        self.verticalLayout_5.addWidget(self.Btn_del)
        spacerItem = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_14 = QtWidgets.QFrame(self.frame_3)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_26.setContentsMargins(0, 0, 5, 5)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_19 = QtWidgets.QFrame(self.frame_14)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_6 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_25.addWidget(self.label_6)
        self.listWidget_selected_group = QtWidgets.QListWidget(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget_selected_group.setFont(font)
        self.listWidget_selected_group.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_selected_group.setObjectName("listWidget_selected_group")
        self.verticalLayout_25.addWidget(self.listWidget_selected_group)
        self.verticalLayout_26.addWidget(self.frame_19)
        self.frame_18 = QtWidgets.QFrame(self.frame_14)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Btn_all_to_group = QtWidgets.QPushButton(self.frame_18)
        self.Btn_all_to_group.setMinimumSize(QtCore.QSize(0, 0))
        self.Btn_all_to_group.setStyleSheet("image: url(:/new/other/other/chevron-up.svg);")
        self.Btn_all_to_group.setText("")
        self.Btn_all_to_group.setObjectName("Btn_all_to_group")
        self.horizontalLayout_11.addWidget(self.Btn_all_to_group)
        self.Btn_to_group = QtWidgets.QPushButton(self.frame_18)
        self.Btn_to_group.setStyleSheet("image: url(:/new/other/other/up-arrow.svg);")
        self.Btn_to_group.setText("")
        self.Btn_to_group.setObjectName("Btn_to_group")
        self.horizontalLayout_11.addWidget(self.Btn_to_group)
        self.Btn_to_free = QtWidgets.QPushButton(self.frame_18)
        self.Btn_to_free.setStyleSheet("image: url(:/new/other/other/down_arrow.svg);")
        self.Btn_to_free.setText("")
        self.Btn_to_free.setObjectName("Btn_to_free")
        self.horizontalLayout_11.addWidget(self.Btn_to_free)
        self.Btn_all_to_free = QtWidgets.QPushButton(self.frame_18)
        self.Btn_all_to_free.setStyleSheet("image: url(:/new/other/other/chevron-down.svg);")
        self.Btn_all_to_free.setText("")
        self.Btn_all_to_free.setObjectName("Btn_all_to_free")
        self.horizontalLayout_11.addWidget(self.Btn_all_to_free)
        self.verticalLayout_26.addWidget(self.frame_18)
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_20.setContentsMargins(0, 0, 5, 5)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_7 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_20.addWidget(self.label_7)
        self.listWidget_free_seq = QtWidgets.QListWidget(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget_free_seq.setFont(font)
        self.listWidget_free_seq.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_free_seq.setObjectName("listWidget_free_seq")
        self.verticalLayout_20.addWidget(self.listWidget_free_seq)
        self.verticalLayout_26.addWidget(self.frame_17)
        self.horizontalLayout_3.addWidget(self.frame_14)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame)
        self.Pages_Widget.addWidget(self.group_page)
        self.simplot_page = QtWidgets.QWidget()
        self.simplot_page.setObjectName("simplot_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.simplot_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.simplot_page)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Disploter_option_bar = QtWidgets.QFrame(self.frame_6)
        self.Disploter_option_bar.setMinimumSize(QtCore.QSize(145, 0))
        self.Disploter_option_bar.setMaximumSize(QtCore.QSize(81, 16777215))
        self.Disploter_option_bar.setStyleSheet("")
        self.Disploter_option_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Disploter_option_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Disploter_option_bar.setObjectName("Disploter_option_bar")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Disploter_option_bar)
        self.verticalLayout_8.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Btn_start_simplot = QtWidgets.QPushButton(self.Disploter_option_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_start_simplot.sizePolicy().hasHeightForWidth())
        self.Btn_start_simplot.setSizePolicy(sizePolicy)
        self.Btn_start_simplot.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_start_simplot.setFont(font)
        self.Btn_start_simplot.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/launch_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/launch_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/launch_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/launch_pressed.svg);\n"
"}")
        self.Btn_start_simplot.setText("")
        self.Btn_start_simplot.setObjectName("Btn_start_simplot")
        self.verticalLayout_8.addWidget(self.Btn_start_simplot)
        self.Btn_model_settings = QtWidgets.QPushButton(self.Disploter_option_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_model_settings.sizePolicy().hasHeightForWidth())
        self.Btn_model_settings.setSizePolicy(sizePolicy)
        self.Btn_model_settings.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_model_settings.setFont(font)
        self.Btn_model_settings.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/settings_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/settings_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/settings_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/settings_pressed.svg);\n"
"}")
        self.Btn_model_settings.setText("")
        self.Btn_model_settings.setObjectName("Btn_model_settings")
        self.verticalLayout_8.addWidget(self.Btn_model_settings)
        self.Btn_plot_window = QtWidgets.QPushButton(self.Disploter_option_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_plot_window.sizePolicy().hasHeightForWidth())
        self.Btn_plot_window.setSizePolicy(sizePolicy)
        self.Btn_plot_window.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_plot_window.setFont(font)
        self.Btn_plot_window.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/View_new_window_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/View_new_window_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/View_new_window_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/View_new_window_pressed.svg);\n"
"}")
        self.Btn_plot_window.setText("")
        self.Btn_plot_window.setObjectName("Btn_plot_window")
        self.verticalLayout_8.addWidget(self.Btn_plot_window)
        self.Btn_quality = QtWidgets.QPushButton(self.Disploter_option_bar)
        self.Btn_quality.setMinimumSize(QtCore.QSize(145, 60))
        self.Btn_quality.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/view_quality_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/view_quality_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/view_quality_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/view_quality_pressed.svg);\n"
"}")
        self.Btn_quality.setText("")
        self.Btn_quality.setObjectName("Btn_quality")
        self.verticalLayout_8.addWidget(self.Btn_quality)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Disploter_option_bar)
        self.groupBox_3.setMinimumSize(QtCore.QSize(145, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 1)
        self.verticalLayout_22.setSpacing(1)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.comboBox_simplot_refseq = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_simplot_refseq.setMinimumSize(QtCore.QSize(137, 0))
        self.comboBox_simplot_refseq.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_simplot_refseq.setFont(font)
        self.comboBox_simplot_refseq.setStyleSheet("QComboBox{\n"
"min-width: 135 px;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"min-width : 175px;\n"
"}\n"
"\n"
"QComboBox:pressed{\n"
"min-width : 175px;\n"
"}")
        self.comboBox_simplot_refseq.setEditable(False)
        self.comboBox_simplot_refseq.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_simplot_refseq.setObjectName("comboBox_simplot_refseq")
        self.verticalLayout_22.addWidget(self.comboBox_simplot_refseq)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_6.addWidget(self.Disploter_option_bar)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_9.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, 10, -1, 5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.Pages_Widget.addWidget(self.simplot_page)
        self.bootscan_page = QtWidgets.QWidget()
        self.bootscan_page.setObjectName("bootscan_page")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.bootscan_page)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_7 = QtWidgets.QFrame(self.bootscan_page)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Disploter_option_bar_2 = QtWidgets.QFrame(self.frame_7)
        self.Disploter_option_bar_2.setMinimumSize(QtCore.QSize(145, 0))
        self.Disploter_option_bar_2.setMaximumSize(QtCore.QSize(81, 16777215))
        self.Disploter_option_bar_2.setStyleSheet("")
        self.Disploter_option_bar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Disploter_option_bar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Disploter_option_bar_2.setObjectName("Disploter_option_bar_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.Disploter_option_bar_2)
        self.verticalLayout_15.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_15.setSpacing(1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Btn_start_bootscan = QtWidgets.QPushButton(self.Disploter_option_bar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_start_bootscan.sizePolicy().hasHeightForWidth())
        self.Btn_start_bootscan.setSizePolicy(sizePolicy)
        self.Btn_start_bootscan.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_start_bootscan.setFont(font)
        self.Btn_start_bootscan.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/launch_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/launch_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/launch_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/launch_pressed.svg);\n"
"}")
        self.Btn_start_bootscan.setText("")
        self.Btn_start_bootscan.setObjectName("Btn_start_bootscan")
        self.verticalLayout_15.addWidget(self.Btn_start_bootscan)
        self.Btn_bootscan_settings = QtWidgets.QPushButton(self.Disploter_option_bar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_bootscan_settings.sizePolicy().hasHeightForWidth())
        self.Btn_bootscan_settings.setSizePolicy(sizePolicy)
        self.Btn_bootscan_settings.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_bootscan_settings.setFont(font)
        self.Btn_bootscan_settings.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/settings_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/settings_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/settings_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/settings_pressed.svg);\n"
"}")
        self.Btn_bootscan_settings.setText("")
        self.Btn_bootscan_settings.setObjectName("Btn_bootscan_settings")
        self.verticalLayout_15.addWidget(self.Btn_bootscan_settings)
        self.Btn_plot_window_bootscan = QtWidgets.QPushButton(self.Disploter_option_bar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_plot_window_bootscan.sizePolicy().hasHeightForWidth())
        self.Btn_plot_window_bootscan.setSizePolicy(sizePolicy)
        self.Btn_plot_window_bootscan.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_plot_window_bootscan.setFont(font)
        self.Btn_plot_window_bootscan.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/View_new_window_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/View_new_window_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/View_new_window_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/View_new_window_pressed.svg);\n"
"}")
        self.Btn_plot_window_bootscan.setText("")
        self.Btn_plot_window_bootscan.setObjectName("Btn_plot_window_bootscan")
        self.verticalLayout_15.addWidget(self.Btn_plot_window_bootscan)
        self.groupBox = QtWidgets.QGroupBox(self.Disploter_option_bar_2)
        self.groupBox.setMaximumSize(QtCore.QSize(145, 16777215))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 1)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.comboBox_Bootscan_refseq = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Bootscan_refseq.setMinimumSize(QtCore.QSize(130, 0))
        self.comboBox_Bootscan_refseq.setMaximumSize(QtCore.QSize(145, 16777215))
        self.comboBox_Bootscan_refseq.setStyleSheet("")
        self.comboBox_Bootscan_refseq.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_Bootscan_refseq.setObjectName("comboBox_Bootscan_refseq")
        self.verticalLayout_11.addWidget(self.comboBox_Bootscan_refseq)
        self.verticalLayout_15.addWidget(self.groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.horizontalLayout_7.addWidget(self.Disploter_option_bar_2)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.verticalLayout_16.addWidget(self.frame_7)
        self.Pages_Widget.addWidget(self.bootscan_page)
        self.findSites_page = QtWidgets.QWidget()
        self.findSites_page.setObjectName("findSites_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.findSites_page)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_10 = QtWidgets.QFrame(self.findSites_page)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_20 = QtWidgets.QFrame(self.frame_10)
        self.frame_20.setMinimumSize(QtCore.QSize(145, 0))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.Btn_begin_findSites = QtWidgets.QPushButton(self.frame_20)
        self.Btn_begin_findSites.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_begin_findSites.setFont(font)
        self.Btn_begin_findSites.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/launch_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/launch_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/launch_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/launch_pressed.svg);\n"
"}")
        self.Btn_begin_findSites.setText("")
        self.Btn_begin_findSites.setObjectName("Btn_begin_findSites")
        self.verticalLayout_23.addWidget(self.Btn_begin_findSites)
        self.Btn_save_findSite = QtWidgets.QPushButton(self.frame_20)
        self.Btn_save_findSite.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_save_findSite.setFont(font)
        self.Btn_save_findSite.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    image: url(:/new/active/active/save_text_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/save_text_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/save_text_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/save_text_pressed.svg);\n"
"}")
        self.Btn_save_findSite.setText("")
        self.Btn_save_findSite.setObjectName("Btn_save_findSite")
        self.verticalLayout_23.addWidget(self.Btn_save_findSite)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem4)
        self.horizontalLayout_12.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_10)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_17.setContentsMargins(0, 0, 9, 9)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_outgroup = QtWidgets.QComboBox(self.frame_21)
        self.comboBox_outgroup.setObjectName("comboBox_outgroup")
        self.gridLayout_2.addWidget(self.comboBox_outgroup, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_query = QtWidgets.QComboBox(self.frame_21)
        self.comboBox_query.setObjectName("comboBox_query")
        self.gridLayout_2.addWidget(self.comboBox_query, 1, 1, 1, 1)
        self.comboBox_ref1 = QtWidgets.QComboBox(self.frame_21)
        self.comboBox_ref1.setObjectName("comboBox_ref1")
        self.gridLayout_2.addWidget(self.comboBox_ref1, 2, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 2, 1, 1)
        self.comboBox_ref2 = QtWidgets.QComboBox(self.frame_21)
        self.comboBox_ref2.setObjectName("comboBox_ref2")
        self.gridLayout_2.addWidget(self.comboBox_ref2, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 5, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_2)
        self.frame_12 = QtWidgets.QFrame(self.frame_21)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setLineWidth(2)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_18.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_18.setSpacing(5)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.findSite_output_browser = QtWidgets.QPlainTextEdit(self.frame_12)
        self.findSite_output_browser.setStyleSheet("\n"
"QPlainTextEdit {\n"
"    background-color: white;\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"  width: 15px;\n"
"  background: #f1f1f1;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  background: #888;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"  border: 2px solid gray;\n"
"  background: #f1f1f1;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"  border: 2px solid gray;\n"
"  background: #f1f1f1;\n"
"}\n"
"\n"
"QScrollBar::handle:hover:vertical {\n"
"  background: #555;\n"
"}")
        self.findSite_output_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.findSite_output_browser.setReadOnly(True)
        self.findSite_output_browser.setPlainText("")
        self.findSite_output_browser.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.findSite_output_browser.setBackgroundVisible(True)
        self.findSite_output_browser.setObjectName("findSite_output_browser")
        self.verticalLayout_18.addWidget(self.findSite_output_browser)
        self.verticalLayout_17.addWidget(self.frame_12)
        self.horizontalLayout_12.addWidget(self.frame_21)
        self.verticalLayout_12.addWidget(self.frame_10)
        self.Pages_Widget.addWidget(self.findSites_page)
        self.network_page = QtWidgets.QWidget()
        self.network_page.setObjectName("network_page")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.network_page)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_15 = QtWidgets.QFrame(self.network_page)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Disploter_option_bar_3 = QtWidgets.QFrame(self.frame_15)
        self.Disploter_option_bar_3.setMinimumSize(QtCore.QSize(145, 0))
        self.Disploter_option_bar_3.setMaximumSize(QtCore.QSize(81, 16777215))
        self.Disploter_option_bar_3.setStyleSheet("")
        self.Disploter_option_bar_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Disploter_option_bar_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Disploter_option_bar_3.setObjectName("Disploter_option_bar_3")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.Disploter_option_bar_3)
        self.verticalLayout_21.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.Btn_start_sp_network = QtWidgets.QPushButton(self.Disploter_option_bar_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_start_sp_network.sizePolicy().hasHeightForWidth())
        self.Btn_start_sp_network.setSizePolicy(sizePolicy)
        self.Btn_start_sp_network.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_start_sp_network.setFont(font)
        self.Btn_start_sp_network.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/launch_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/launch_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/launch_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/launch_pressed.svg);\n"
"}")
        self.Btn_start_sp_network.setText("")
        self.Btn_start_sp_network.setObjectName("Btn_start_sp_network")
        self.verticalLayout_21.addWidget(self.Btn_start_sp_network)
        self.Btn_network_settings = QtWidgets.QPushButton(self.Disploter_option_bar_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_network_settings.sizePolicy().hasHeightForWidth())
        self.Btn_network_settings.setSizePolicy(sizePolicy)
        self.Btn_network_settings.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_network_settings.setFont(font)
        self.Btn_network_settings.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/settings_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/settings_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/settings_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/settings_pressed.svg);\n"
"}")
        self.Btn_network_settings.setText("")
        self.Btn_network_settings.setObjectName("Btn_network_settings")
        self.verticalLayout_21.addWidget(self.Btn_network_settings)
        self.Btn_save_html = QtWidgets.QPushButton(self.Disploter_option_bar_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_save_html.sizePolicy().hasHeightForWidth())
        self.Btn_save_html.setSizePolicy(sizePolicy)
        self.Btn_save_html.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_save_html.setFont(font)
        self.Btn_save_html.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/save_html_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/save_html_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/save_html_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/save_html_pressed.svg);\n"
"}")
        self.Btn_save_html.setText("")
        self.Btn_save_html.setObjectName("Btn_save_html")
        self.verticalLayout_21.addWidget(self.Btn_save_html)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem7)
        self.horizontalLayout_9.addWidget(self.Disploter_option_bar_3)
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Vlayout_network = QtWidgets.QVBoxLayout()
        self.Vlayout_network.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Vlayout_network.setContentsMargins(0, 10, -1, 5)
        self.Vlayout_network.setObjectName("Vlayout_network")
        self.horizontalLayout_10.addLayout(self.Vlayout_network)
        self.horizontalLayout_9.addWidget(self.frame_16)
        self.verticalLayout_24.addWidget(self.frame_15)
        self.Pages_Widget.addWidget(self.network_page)
        self.recombination_page = QtWidgets.QWidget()
        self.recombination_page.setObjectName("recombination_page")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.recombination_page)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_11 = QtWidgets.QFrame(self.recombination_page)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Disploter_option_bar_6 = QtWidgets.QFrame(self.frame_11)
        self.Disploter_option_bar_6.setMinimumSize(QtCore.QSize(145, 0))
        self.Disploter_option_bar_6.setMaximumSize(QtCore.QSize(81, 16777215))
        self.Disploter_option_bar_6.setStyleSheet("")
        self.Disploter_option_bar_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Disploter_option_bar_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Disploter_option_bar_6.setObjectName("Disploter_option_bar_6")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.Disploter_option_bar_6)
        self.verticalLayout_29.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_29.setSpacing(1)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.Btn_start_recomb_test = QtWidgets.QPushButton(self.Disploter_option_bar_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_start_recomb_test.sizePolicy().hasHeightForWidth())
        self.Btn_start_recomb_test.setSizePolicy(sizePolicy)
        self.Btn_start_recomb_test.setMinimumSize(QtCore.QSize(145, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Btn_start_recomb_test.setFont(font)
        self.Btn_start_recomb_test.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/active/active/launch_active.svg);\n"
" }\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/hover/hover/launch_hover.svg);\n"
"}\n"
"QPushButton:disabled{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/disabled/disabled/launch_disabled.svg);\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 0px;\n"
"    \n"
"    image: url(:/new/pressed/pressed/launch_pressed.svg);\n"
"}")
        self.Btn_start_recomb_test.setText("")
        self.Btn_start_recomb_test.setObjectName("Btn_start_recomb_test")
        self.verticalLayout_29.addWidget(self.Btn_start_recomb_test)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem8)
        self.horizontalLayout_8.addWidget(self.Disploter_option_bar_6)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_25 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy)
        self.frame_25.setMinimumSize(QtCore.QSize(851, 303))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_25)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioBtn_dna = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtn_dna.setAutoExclusive(True)
        self.radioBtn_dna.setObjectName("radioBtn_dna")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioBtn_dna)
        self.gridLayout_4.addWidget(self.radioBtn_dna, 2, 0, 1, 1)
        self.radioBtn_other = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtn_other.setObjectName("radioBtn_other")
        self.buttonGroup_2.addButton(self.radioBtn_other)
        self.gridLayout_4.addWidget(self.radioBtn_other, 2, 2, 1, 1)
        self.radioBtn_use_og_seqs = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtn_use_og_seqs.setChecked(True)
        self.radioBtn_use_og_seqs.setObjectName("radioBtn_use_og_seqs")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioBtn_use_og_seqs)
        self.gridLayout_4.addWidget(self.radioBtn_use_og_seqs, 0, 1, 1, 1)
        self.radioBtn_protein = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtn_protein.setObjectName("radioBtn_protein")
        self.buttonGroup_2.addButton(self.radioBtn_protein)
        self.gridLayout_4.addWidget(self.radioBtn_protein, 2, 1, 1, 1)
        self.radioBtn_use_group_seqs = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtn_use_group_seqs.setObjectName("radioBtn_use_group_seqs")
        self.buttonGroup.addButton(self.radioBtn_use_group_seqs)
        self.gridLayout_4.addWidget(self.radioBtn_use_group_seqs, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.radioBtn_phi_test = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtn_phi_test.setChecked(True)
        self.radioBtn_phi_test.setObjectName("radioBtn_phi_test")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioBtn_phi_test)
        self.gridLayout_4.addWidget(self.radioBtn_phi_test, 4, 0, 1, 1)
        self.radioBtn_profile_test = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtn_profile_test.setObjectName("radioBtn_profile_test")
        self.buttonGroup_3.addButton(self.radioBtn_profile_test)
        self.gridLayout_4.addWidget(self.radioBtn_profile_test, 4, 1, 1, 1)
        self.radioBtn_dist_recomb_test = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBtn_dist_recomb_test.setObjectName("radioBtn_dist_recomb_test")
        self.buttonGroup_3.addButton(self.radioBtn_dist_recomb_test)
        self.gridLayout_4.addWidget(self.radioBtn_dist_recomb_test, 4, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.recomb_stacked_pages = QtWidgets.QStackedWidget(self.frame_25)
        self.recomb_stacked_pages.setObjectName("recomb_stacked_pages")
        self.phi_test_option_page = QtWidgets.QWidget()
        self.phi_test_option_page.setObjectName("phi_test_option_page")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.phi_test_option_page)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_26 = QtWidgets.QFrame(self.phi_test_option_page)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_26)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.spinBox_phi_test_window = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_phi_test_window.setMinimum(10)
        self.spinBox_phi_test_window.setMaximum(1000)
        self.spinBox_phi_test_window.setSingleStep(10)
        self.spinBox_phi_test_window.setProperty("value", 100)
        self.spinBox_phi_test_window.setObjectName("spinBox_phi_test_window")
        self.gridLayout_5.addWidget(self.spinBox_phi_test_window, 1, 1, 1, 1)
        self.spinBox_phi_test_perm = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_phi_test_perm.setMinimum(100)
        self.spinBox_phi_test_perm.setMaximum(10000)
        self.spinBox_phi_test_perm.setSingleStep(100)
        self.spinBox_phi_test_perm.setProperty("value", 1000)
        self.spinBox_phi_test_perm.setObjectName("spinBox_phi_test_perm")
        self.gridLayout_5.addWidget(self.spinBox_phi_test_perm, 0, 1, 1, 1)
        self.checkBox_phi_test_perm = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_phi_test_perm.setChecked(True)
        self.checkBox_phi_test_perm.setObjectName("checkBox_phi_test_perm")
        self.gridLayout_5.addWidget(self.checkBox_phi_test_perm, 0, 0, 1, 1)
        self.checkBox_phi_test_other_tests = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_phi_test_other_tests.setObjectName("checkBox_phi_test_other_tests")
        self.gridLayout_5.addWidget(self.checkBox_phi_test_other_tests, 2, 0, 1, 1)
        self.verticalLayout_33.addWidget(self.groupBox_4)
        self.verticalLayout_32.addWidget(self.frame_26)
        self.recomb_stacked_pages.addWidget(self.phi_test_option_page)
        self.phi_profile_option_page = QtWidgets.QWidget()
        self.phi_profile_option_page.setObjectName("phi_profile_option_page")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.phi_profile_option_page)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.frame_27 = QtWidgets.QFrame(self.phi_profile_option_page)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_27)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 2, 0, 1, 1)
        self.spinBox_profile_window = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_profile_window.setMinimum(10)
        self.spinBox_profile_window.setMaximum(1000)
        self.spinBox_profile_window.setSingleStep(10)
        self.spinBox_profile_window.setProperty("value", 100)
        self.spinBox_profile_window.setObjectName("spinBox_profile_window")
        self.gridLayout_6.addWidget(self.spinBox_profile_window, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 1, 0, 1, 1)
        self.spinBox_profile_perms = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_profile_perms.setMinimum(100)
        self.spinBox_profile_perms.setMaximum(10000)
        self.spinBox_profile_perms.setSingleStep(100)
        self.spinBox_profile_perms.setProperty("value", 1000)
        self.spinBox_profile_perms.setObjectName("spinBox_profile_perms")
        self.gridLayout_6.addWidget(self.spinBox_profile_perms, 0, 1, 1, 1)
        self.checkBox_profile_perm = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_profile_perm.setChecked(True)
        self.checkBox_profile_perm.setTristate(False)
        self.checkBox_profile_perm.setObjectName("checkBox_profile_perm")
        self.gridLayout_6.addWidget(self.checkBox_profile_perm, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 3, 0, 1, 1)
        self.spinBox_profile_break_window = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_profile_break_window.setMinimum(10)
        self.spinBox_profile_break_window.setMaximum(10000)
        self.spinBox_profile_break_window.setSingleStep(10)
        self.spinBox_profile_break_window.setProperty("value", 1000)
        self.spinBox_profile_break_window.setObjectName("spinBox_profile_break_window")
        self.gridLayout_6.addWidget(self.spinBox_profile_break_window, 2, 1, 1, 1)
        self.spinBox_profile_step = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_profile_step.setMinimum(10)
        self.spinBox_profile_step.setMaximum(1000)
        self.spinBox_profile_step.setProperty("value", 25)
        self.spinBox_profile_step.setObjectName("spinBox_profile_step")
        self.gridLayout_6.addWidget(self.spinBox_profile_step, 3, 1, 1, 1)
        self.verticalLayout_34.addWidget(self.groupBox_5)
        self.verticalLayout_35.addWidget(self.frame_27)
        self.recomb_stacked_pages.addWidget(self.phi_profile_option_page)
        self.gridLayout_3.addWidget(self.recomb_stacked_pages, 1, 0, 1, 1)
        self.horizontalLayout_17.addLayout(self.gridLayout_3)
        self.frame_28 = QtWidgets.QFrame(self.frame_25)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.textEdit = QtWidgets.QTextEdit(self.frame_28)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_36.addWidget(self.textEdit)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_28)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_recomb_multiproc = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_recomb_multiproc.setObjectName("checkBox_recomb_multiproc")
        self.gridLayout_7.addWidget(self.checkBox_recomb_multiproc, 0, 0, 1, 1)
        self.checkBox_recomb_verbose = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_recomb_verbose.setObjectName("checkBox_recomb_verbose")
        self.gridLayout_7.addWidget(self.checkBox_recomb_verbose, 0, 1, 1, 1)
        self.checkBox_recomb_save_output = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_recomb_save_output.setObjectName("checkBox_recomb_save_output")
        self.gridLayout_7.addWidget(self.checkBox_recomb_save_output, 1, 0, 1, 1)
        self.verticalLayout_36.addWidget(self.groupBox_6)
        self.horizontalLayout_17.addWidget(self.frame_28)
        self.verticalLayout_30.addWidget(self.frame_25)
        self.frame_22 = QtWidgets.QFrame(self.frame_13)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_22)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_31.addWidget(self.textEdit_2)
        self.verticalLayout_30.addWidget(self.frame_22)
        self.horizontalLayout_8.addWidget(self.frame_13)
        self.verticalLayout_19.addWidget(self.frame_11)
        self.Pages_Widget.addWidget(self.recombination_page)
        self.verticalLayout_2.addWidget(self.Pages_Widget)
        self.horizontalLayout.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages_Widget.setCurrentIndex(0)
        self.recomb_stacked_pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SimPlot++"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">List of current groups (at least 2 groups needed)</span></p></body></html>"))
        self.Btn_add.setText(_translate("MainWindow", "New group"))
        self.Btn_del.setText(_translate("MainWindow", "Delete group"))
        self.label_6.setText(_translate("MainWindow", "Select Group"))
        self.listWidget_selected_group.setSortingEnabled(True)
        self.label_7.setText(_translate("MainWindow", "Ungrouped Sequences"))
        self.listWidget_free_seq.setSortingEnabled(True)
        self.groupBox_3.setTitle(_translate("MainWindow", "Reference Group"))
        self.groupBox.setTitle(_translate("MainWindow", "Reference"))
        self.label_4.setText(_translate("MainWindow", "Ref2"))
        self.label_3.setText(_translate("MainWindow", "Ref1"))
        self.label_2.setText(_translate("MainWindow", "Query"))
        self.label_5.setText(_translate("MainWindow", "Outgroup"))
        self.findSite_output_browser.setPlaceholderText(_translate("MainWindow", "Select 4 distinct sequences and press START to begin analysis"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Data input"))
        self.radioBtn_dna.setText(_translate("MainWindow", "DNA"))
        self.radioBtn_other.setText(_translate("MainWindow", "Other"))
        self.radioBtn_use_og_seqs.setText(_translate("MainWindow", "Use original data file"))
        self.radioBtn_protein.setText(_translate("MainWindow", "Amino Acids"))
        self.radioBtn_use_group_seqs.setText(_translate("MainWindow", "Use sequence groups"))
        self.label_8.setText(_translate("MainWindow", "Data type"))
        self.label_13.setText(_translate("MainWindow", "Test to run"))
        self.radioBtn_phi_test.setText(_translate("MainWindow", "Phi-test"))
        self.radioBtn_profile_test.setText(_translate("MainWindow", "Phi Profile test"))
        self.radioBtn_dist_recomb_test.setText(_translate("MainWindow", "Proportion test"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Phi-Test options"))
        self.label_9.setText(_translate("MainWindow", "Window size"))
        self.checkBox_phi_test_perm.setText(_translate("MainWindow", "Permutations"))
        self.checkBox_phi_test_other_tests.setText(_translate("MainWindow", "Compute NSS and Max Chi tests"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Phi Profile options"))
        self.label_11.setText(_translate("MainWindow", "Break window"))
        self.label_10.setText(_translate("MainWindow", "Window size"))
        self.checkBox_profile_perm.setText(_translate("MainWindow", "Permutations"))
        self.label_12.setText(_translate("MainWindow", "Step size"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Miscellaneous"))
        self.checkBox_recomb_multiproc.setText(_translate("MainWindow", "Multiprocessing"))
        self.checkBox_recomb_verbose.setText(_translate("MainWindow", "Verbose output"))
        self.checkBox_recomb_save_output.setText(_translate("MainWindow", "Save output as .txt to data file location"))
