# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\group_list_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_group_list_widget(object):
    def setupUi(self, group_list_widget):
        group_list_widget.setObjectName("group_list_widget")
        group_list_widget.resize(300, 75)
        group_list_widget.setMinimumSize(QtCore.QSize(300, 0))
        group_list_widget.setMaximumSize(QtCore.QSize(300, 75))
        group_list_widget.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(group_list_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(group_list_widget)
        self.frame.setStyleSheet("border-top: 1px solid black;\n"
"\n"
"border-bottom: 1px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_group_color = QtWidgets.QPushButton(self.frame_2)
        self.Btn_group_color.setMinimumSize(QtCore.QSize(60, 60))
        self.Btn_group_color.setStyleSheet("border: 0px;\n"
"background-color: rgb(0, 170, 255);\n"
"border-radius: 30px;")
        self.Btn_group_color.setText("")
        self.Btn_group_color.setFlat(False)
        self.Btn_group_color.setObjectName("Btn_group_color")
        self.verticalLayout_2.addWidget(self.Btn_group_color)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_group_name = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_group_name.setStyleSheet("border: 1px solid black")
        self.lineEdit_group_name.setText("")
        self.lineEdit_group_name.setObjectName("lineEdit_group_name")
        self.verticalLayout_3.addWidget(self.lineEdit_group_name)
        self.label_seq_length = QtWidgets.QLabel(self.frame_4)
        self.label_seq_length.setStyleSheet("border: 0px;")
        self.label_seq_length.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_seq_length.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_seq_length.setLineWidth(-22)
        self.label_seq_length.setText("")
        self.label_seq_length.setObjectName("label_seq_length")
        self.verticalLayout_3.addWidget(self.label_seq_length)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(group_list_widget)
        QtCore.QMetaObject.connectSlotsByName(group_list_widget)

    def retranslateUi(self, group_list_widget):
        _translate = QtCore.QCoreApplication.translate
        group_list_widget.setWindowTitle(_translate("group_list_widget", "Form"))
