# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\file_info_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 213)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(502, 0))
        Dialog.setMaximumSize(QtCore.QSize(502, 213))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 140, 535, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_format = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_format.setObjectName("comboBox_format")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_format)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_datatype = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_datatype.setObjectName("comboBox_datatype")
        self.comboBox_datatype.addItem("")
        self.comboBox_datatype.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_datatype)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(11, 11, 481, 121))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "File Format Finder"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>File format:</p></body></html>"))
        self.comboBox_format.setItemText(0, _translate("Dialog", "fasta"))
        self.comboBox_format.setItemText(1, _translate("Dialog", "nexus"))
        self.comboBox_format.setItemText(2, _translate("Dialog", "pir"))
        self.comboBox_format.setItemText(3, _translate("Dialog", "phylip"))
        self.comboBox_format.setItemText(4, _translate("Dialog", "stockholm"))
        self.comboBox_format.setItemText(5, _translate("Dialog", "clustal"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>Datatype:</p></body></html>"))
        self.comboBox_datatype.setItemText(0, _translate("Dialog", "DNA"))
        self.comboBox_datatype.setItemText(1, _translate("Dialog", "protein"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">The default file formats (Fasta/Nexus) and/or the datatype (nt/aa) </span></p><p><span style=\" font-size:9pt; font-weight:600;\">could not be detetcted adequately.</span></p><p>It is recommended to use these formats for optimal software stability.</p><p>If you wish to continue and are sure that your file is parseable by biopython, enter the file format and datatype manually below.</p><p>Otherwise, press cancel to return to the main window.</p></body></html>"))
